### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by RazK** [mishaelnuh/RodSteward-GH#10]
Hey!

I'm Raz, a computer science + design student from Israel.
I'm trying to use your cool library for a project I'm working on in my design degree, but with no success.

I downloaded the latest release, unlocked the zip, and extracted the files to a 'RodSteward' folder I created inside Grasshopper's Components folder (That's the typical install process, I followed it because your README did not mention any specific install details...)
However, it seems like the library was not correctly installed: 

![image](https://user-images.githubusercontent.com/6826569/105628970-e7876b00-5e48-11eb-8774-3516080b6dfe.png)

Will you help me get this working?
I'll mention you in any future publication of the project, of course :)

Thanks!
Raz Karl
www.razkarl.com

**Comment by RazK** [comment]
@mishaelnuh

**Comment by RazK** [comment]
Problem solved!
It seems that all I had to do is manually go over all the files extracted from the .zip and unblock them one by one.
![image](https://user-images.githubusercontent.com/6826569/105629348-2ae2d900-5e4b-11eb-8ba0-b8acc3400005.png)


This is a bit odd since I unblocked the .zip file before extracting it... But now everything works! 
I'm off to explore the library, looks very cool so far :)

![image](https://user-images.githubusercontent.com/6826569/105629337-1c94bd00-5e4b-11eb-8041-abf9e56133a9.png)

**Comment by hakrek** [comment]
@RazK Hi! I'm having the same issue when trying to install for Rhino 6 (Windows), but following what you described above as your solution I couldn't make it work.. :'( 
From what I understand, you extracted the RodSteward .zip file into the GH Components folder (without unblocking the downloaded .zip file first) and then proceeded to manually unblock all the blocked files that resulted from extracting, am I right? 
After that did you get the RodSteward plugin to appear on your GH plugins bar? Because I'm not getting it..

Could you please specify if there were any other steps involved or if there's something more I'm missing? 
thanks a lot!!

**Comment by mishaelnuh** [comment]
Hi @hakrek. I'd suggest unblocking both the zip and the files inside and seeing what happens. Alternatively, I found this post about automatic unblocking GH plugins using a C# block: https://www.grasshopper3d.com/m/blogpost?id=2985220%3ABlogPost%3A1345130. Perhaps that may help.

Hope that helps!

**Comment by hakrek** [comment]
@mishaelnuh thanks for your comment! So far I've tried: 
-unblocking the .zip file and then extracting its contents to the Components (when I tried unlocking them too the option was not there)
- unzipping the .zip file without unblocking and then unblocking its extracted files manually.
- using the C# script that you mentioned above. 

None of it has worked so far. I tried both in Rhino 6 and 7 (Evaluation version) both in Windows. :'(

any other ideas? could you describe me the steps I should follow? or provide a screenshot of how the component would look when its installed in GH?

**Comment by mishaelnuh** [comment]
I've tried re-installing and these steps seem to work:
- Unzip to a folder within the Components folder -> `%AppData%\Roaming\Grasshopper\Libraries\RodStewardGH`.
- Unblock RodSteward.gha. If the unblock option is not there, it's likely that the plugin is already unblocked.

Here are some screenshots of this:
![image](https://user-images.githubusercontent.com/45694155/110240677-fe8ba380-7f44-11eb-8e71-558703fe9a59.png)
![image](https://user-images.githubusercontent.com/45694155/110240699-1bc07200-7f45-11eb-9524-2b9ddcc1e7b0.png)
![image](https://user-images.githubusercontent.com/45694155/110240617-bb313500-7f44-11eb-9584-9f7e13b46d9c.png)

**Comment by hakrek** [comment]
@mishaelnuh thank you so much for the detailed response! The strange part is that I don't even find a RodSteward.gha file in the folder after extraction...Am I doing something wrong from the very start? The .zip file I am downloading is the one from this section of your github page: 
![Screenshot_1](https://user-images.githubusercontent.com/44825334/110310987-85747500-8046-11eb-8e86-18e93ea2ff6f.png)

is this correct? if not please send me the .zip file I should be using!

**Comment by mishaelnuh** [comment]
@hakrek the plugin file is actually in the releases page: https://github.com/mishaelnuh/RodSteward-GH/releases. If you go to assets under the latest release you'll find the zip file. The zip you've downloaded is for the source code and if you wish to compile the plugin manually.
